# Site settings
title: Competitive programming notebook
email: exoji2e@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Måns Magnusson
github_username:  exoji2e

domain: exoji2e.github.io  # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://exoji2e.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /notebook

# Build settings
markdown: kramdown

highlighter: rouge

